New Patient Grouping and Priority examples
canvas-medical/open-source-sdk pull request #20
Opened 2022-07-29 08:44 UTC by jacob-morrison-22

2022-07-29 16:48 UTC, aduane requested changes

2022-07-29 16:48 UTC, aduane commented on canvas_workflow_helpers/protocols/patient_grouping.py
> +        patient_group = self.patient.groups.filter(name=self.GROUP_NAME).records
I don't think we should filter by name. Let's just hardcode the UUID. That way, we don't have to include any group information as context in the protocol.

2022-08-02 20:28 UTC, jacob-morrison-22 commented on canvas_workflow_helpers/protocols/patient_grouping.py
> +        patient_group = self.patient.groups.filter(name=self.GROUP_NAME).records
hardcoded uuid for this protocol

2022-08-02 20:55 UTC, aduane requested changes
I don't think we should put this customer-specific protocol in our open source repo.

2022-08-04 18:13 UTC, jacob-morrison-22 commented
> I don't think we should put this customer-specific protocol in our open source repo.

when i spoke with @eabruzzese about this he said as long as the protocol is generic enough, it should go in here as an example. I removed the identifying information, does this work for you? @aduane

2022-08-04 18:17 UTC, aduane commented on canvas_workflow_helpers/protocols/patient_grouping.py
> +    CONSENT_CODE = '<CODING_FOR_CONSENT>'
```suggestion
    CONSENT_CODE = 'A0001' # replace with your opt-out consent's coding
```

2022-08-04 18:21 UTC, jacob-morrison-22 commented on canvas_workflow_helpers/protocols/patient_grouping.py
> +        patient_group_uuid = '<UUID_OF_PATIENT_GROUP>'
done

2022-08-04 18:21 UTC, jacob-morrison-22 commented on canvas_workflow_helpers/protocols/patient_grouping.py
> +    CONSENT_CODE = '<CODING_FOR_CONSENT>'
done

2022-08-04 18:29 UTC, aduane approved these changes

2022-08-23 16:58 UTC, rmagier1 commented on canvas_workflow_helpers/protocols/patient_priority.py
> +
Add a new line

2022-08-23 17:01 UTC, rmagier1 commented on canvas_workflow_helpers/protocols/patient_priority.py
> +    INTERNAL = {'Risk_Stratification'}
Can you add a comment on the purpose of this valueset. What is the customer supposed to replace these values with?

2022-08-23 17:08 UTC, rmagier1 commented on canvas_workflow_helpers/protocols/patient_priority.py
> +            'There is currently no action to take, so no recommendations are made.')
```suggestion
            'Protocol that displays patient priority based on Risk Questionnaire. '
            'If the patient does not have a Risk Questionnaire, there is no action '
            'to take, so no recommendations are made.')
```

2022-08-23 17:09 UTC, rmagier1 commented on canvas_workflow_helpers/protocols/patient_priority.py
> +        return result
Should we not return the result if there is no risk score?

2022-08-23 17:20 UTC, jacob-morrison-22 commented on canvas_workflow_helpers/protocols/patient_priority.py
> +        return result
Patterns I've seen in other protocols is to always return result here

2022-08-23 17:21 UTC, jacob-morrison-22 commented on canvas_workflow_helpers/protocols/patient_priority.py
> +            'There is currently no action to take, so no recommendations are made.')
I can just remove the wording about recommendations, its kinda unnecessary and might confuse someone looking at this protocol as an example

2022-08-23 17:59 UTC, jacob-morrison-22 commented on canvas_workflow_helpers/protocols/patient_priority.py
> +
this already has a single new line at the end, should there be two?

2022-08-23 17:59 UTC, jacob-morrison-22 commented on canvas_workflow_helpers/protocols/patient_priority.py
> +    INTERNAL = {'Risk_Stratification'}
done

2022-08-23 18:00 UTC, jacob-morrison-22 commented on canvas_workflow_helpers/protocols/patient_priority.py
> +            'There is currently no action to take, so no recommendations are made.')
removed mentions of recommedations

2022-08-23 18:00 UTC, jacob-morrison-22 commented on canvas_workflow_helpers/protocols/patient_priority.py
> +    if the patient has any. There is currently no action to take, so no recommendations are made.
removed mentions of recommedations

2022-08-23 19:36 UTC, rmagier1 commented on canvas_workflow_helpers/protocols/patient_priority.py
> +    INTERNAL = {'Risk_Stratification'}
It needs to be more specific. What columns or fields in the questionnaire loader did those come from

2022-08-23 20:11 UTC, rmagier1 commented on canvas_workflow_helpers/protocols/patient_priority.py
> +    INTERNAL = {'Risk_Stratification'}
1. Comment for the valueset needs to be like 
```
""" 
  This ValueSet will define the specific Questionnaire that is needed to determine patient's priority. 
"""
```
2.   `# VALUE_SET_NAME can be set to a display name for the Questionnaire we are trying to identify`
3.   `# The name of this variable needs to match the coding system of the questionnaire, while the single value in the set represents the questionnaire's code. These values were passed during Questionnaire Loading`

2022-08-23 22:56 UTC, jacob-morrison-22 commented on canvas_workflow_helpers/protocols/patient_priority.py
> +    INTERNAL = {'Risk_Stratification'}
done

2022-08-24 14:51 UTC, merged